name: Terraform Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tf-fmt-check:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        tf_working_dir: [terraform]
    outputs:
      fmt: ${{ steps.fmt.outcome }} 
    steps:
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 1.1.7
      - uses: actions/checkout@v2
        name: Checkout source code
      - name: Terraform fmt
        id: fmt
        run: terraform fmt --recursive -check
        working-directory: ${{ matrix.tf_working_dir }}
  tf-validate:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        tf_working_dir: [terraform]
    outputs:
      validate: ${{ steps.validate.outcome }}
    steps:
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 1.1.7
      - uses: actions/checkout@v2
        name: Checkout source code
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ matrix.tf_working_dir }}
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ matrix.tf_working_dir }}
  tf-lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        tf_working_dir: [terraform]
    steps:
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 1.1.7
      - uses: actions/checkout@v2
        name: Checkout source code
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ matrix.tf_working_dir }}
      - name: tflint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.github_token }}
          flags: "-c ../.tflint.hcl"
          working_directory: ${{ matrix.tf_working_dir }}
          fail_on_error: "true"
          filter_mode: "nofilter"
  # checkov:
  #   runs-on: ubuntu-18.04
  #   strategy:
  #     matrix:
  #       tf_working_dir: [terraform]
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v2
  #     - name: Run Checkov action
  #       id: checkov
  #       uses: bridgecrewio/checkov-action@master
  #       with:
  #         directory: ${{ matrix.tf_working_dir }}
  #         quiet: true 
  #         framework: terraform 
  docs:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Generate TF Docs
      uses: Dirrk/terraform-docs@v1
      with:
        tf_docs_working_dir: terraform
        tf_docs_output_file: ../TF_DOCS.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'